=begin
#Mooncard API

#Access Mooncard data from anywhere

OpenAPI spec version: 3.0.0
Contact: hello@mooncard.co
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CardsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CardsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CardsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CardsApi' do
    it 'should create an instance of CardsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::CardsApi)
    end
  end

  # unit tests for get_api_v3_cards
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page of results to fetch.
  # @option opts [Integer] :per_page Number of results to return per page.
  # @option opts [String] :card_search_name_cont name LIKE %?%
  # @option opts [String] :card_search_pattern_id_eq pattern_id &#x3D; ?
  # @option opts [String] :card_search_user_profile_id_eq user_profile_id &#x3D; ?
  # @option opts [String] :card_search_status_eq status &#x3D; ?
  # @option opts [String] :card_search_order_by Select which field you want to order the results by
  # @option opts [String] :card_search_order Select whether the results should be sorted in ascending or descending order
  # @return [Array<Card>]
  describe 'get_api_v3_cards test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_api_v3_cards_id
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Card]
  describe 'get_api_v3_cards_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_api_v3_cards_id
  # @param id 
  # @param card 
  # @param [Hash] opts the optional parameters
  # @return [Card]
  describe 'put_api_v3_cards_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
