=begin
#Mooncard API

#Access Mooncard data from anywhere

OpenAPI spec version: 3.0.0
Contact: hello@mooncard.co
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.12

=end

require 'spec_helper'
require 'json'

# Unit tests for Mooncard::MeApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MeApi' do
  before do
    # run before each test
    @instance = Mooncard::MeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MeApi' do
    it 'should create an instance of MeApi' do
      expect(@instance).to be_instance_of(Mooncard::MeApi)
    end
  end

  # unit tests for get
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
