=begin
#Mooncard API

#Access Mooncard data from anywhere

OpenAPI spec version: 3.0.0
Contact: hello@mooncard.co
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.12

=end

# Common files
require 'mooncard-sdk/api_client'
require 'mooncard-sdk/api_error'
require 'mooncard-sdk/version'
require 'mooncard-sdk/configuration'

# Models
require 'mooncard-sdk/models/account'
require 'mooncard-sdk/models/address'
require 'mooncard-sdk/models/analytic_code'
require 'mooncard-sdk/models/business_code'
require 'mooncard-sdk/models/card'
require 'mooncard-sdk/models/card_expense'
require 'mooncard-sdk/models/expense'
require 'mooncard-sdk/models/expense_category'
require 'mooncard-sdk/models/expense_source'
require 'mooncard-sdk/models/km_expense'
require 'mooncard-sdk/models/manual_expense'
require 'mooncard-sdk/models/movement'
require 'mooncard-sdk/models/post_api_v3_analytic_codes'
require 'mooncard-sdk/models/post_api_v3_analytic_codes_analytic_code'
require 'mooncard-sdk/models/post_api_v3_business_codes'
require 'mooncard-sdk/models/post_api_v3_card_activation'
require 'mooncard-sdk/models/post_api_v3_card_activation_card_activation'
require 'mooncard-sdk/models/post_api_v3_card_assign'
require 'mooncard-sdk/models/post_api_v3_card_assign_card_assign'
require 'mooncard-sdk/models/post_api_v3_expense_categories'
require 'mooncard-sdk/models/post_api_v3_expense_categories_expense_category'
require 'mooncard-sdk/models/post_api_v3_receipts'
require 'mooncard-sdk/models/post_api_v3_receipts_receipt'
require 'mooncard-sdk/models/post_api_v3_send_card_pin'
require 'mooncard-sdk/models/post_api_v3_send_card_pin_card_pin'
require 'mooncard-sdk/models/post_api_v3_user_profiles'
require 'mooncard-sdk/models/post_api_v3_user_profiles_user_profile'
require 'mooncard-sdk/models/post_api_v3_webhooks'
require 'mooncard-sdk/models/post_api_v3_webhooks_webhook'
require 'mooncard-sdk/models/put_api_v3_analytic_codes'
require 'mooncard-sdk/models/put_api_v3_analytic_codes_analytic_code'
require 'mooncard-sdk/models/put_api_v3_business_codes'
require 'mooncard-sdk/models/put_api_v3_business_codes_business_code'
require 'mooncard-sdk/models/put_api_v3_cards'
require 'mooncard-sdk/models/put_api_v3_cards_card'
require 'mooncard-sdk/models/put_api_v3_expense_categories'
require 'mooncard-sdk/models/put_api_v3_expense_categories_expense_category'
require 'mooncard-sdk/models/put_api_v3_receipts'
require 'mooncard-sdk/models/put_api_v3_receipts_receipt'
require 'mooncard-sdk/models/put_api_v3_user_profiles'
require 'mooncard-sdk/models/put_api_v3_user_profiles_user_profile'
require 'mooncard-sdk/models/put_api_v3_webhooks'
require 'mooncard-sdk/models/put_api_v3_webhooks_webhook'
require 'mooncard-sdk/models/receipt'
require 'mooncard-sdk/models/user_profile'
require 'mooncard-sdk/models/webhook'

# APIs
require 'mooncard-sdk/api/account_movements_api'
require 'mooncard-sdk/api/accounts_api'
require 'mooncard-sdk/api/analytic_codes_api'
require 'mooncard-sdk/api/business_codes_api'
require 'mooncard-sdk/api/card_activation_api'
require 'mooncard-sdk/api/card_assign_api'
require 'mooncard-sdk/api/cards_api'
require 'mooncard-sdk/api/expense_categories_api'
require 'mooncard-sdk/api/expenses_api'
require 'mooncard-sdk/api/me_api'
require 'mooncard-sdk/api/receipts_api'
require 'mooncard-sdk/api/send_card_pin_api'
require 'mooncard-sdk/api/user_profiles_api'
require 'mooncard-sdk/api/webhooks_api'

module Mooncard
  class << self
    # Customize default settings for the SDK using block.
    #   Mooncard.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
