=begin
#Mooncard API

#Access Mooncard data from anywhere

OpenAPI spec version: 3.0.0
Contact: hello@mooncard.co
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.10

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/account'
require 'swagger_client/models/analytic_code'
require 'swagger_client/models/business_code'
require 'swagger_client/models/card'
require 'swagger_client/models/card_expense'
require 'swagger_client/models/expense'
require 'swagger_client/models/expense_category'
require 'swagger_client/models/expense_source'
require 'swagger_client/models/km_expense'
require 'swagger_client/models/manual_expense'
require 'swagger_client/models/movement'
require 'swagger_client/models/post_api_v3_analytic_codes'
require 'swagger_client/models/post_api_v3_analytic_codes_analytic_code'
require 'swagger_client/models/post_api_v3_business_codes'
require 'swagger_client/models/post_api_v3_expense_categories'
require 'swagger_client/models/post_api_v3_expense_categories_expense_category'
require 'swagger_client/models/put_api_v3_analytic_codes'
require 'swagger_client/models/put_api_v3_analytic_codes_analytic_code'
require 'swagger_client/models/put_api_v3_business_codes'
require 'swagger_client/models/put_api_v3_business_codes_business_code'
require 'swagger_client/models/put_api_v3_cards'
require 'swagger_client/models/put_api_v3_cards_card'
require 'swagger_client/models/put_api_v3_expense_categories'
require 'swagger_client/models/put_api_v3_expense_categories_expense_category'

# APIs
require 'swagger_client/api/account_movements_api'
require 'swagger_client/api/accounts_api'
require 'swagger_client/api/analytic_codes_api'
require 'swagger_client/api/business_codes_api'
require 'swagger_client/api/cards_api'
require 'swagger_client/api/expense_categories_api'
require 'swagger_client/api/expenses_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
